### ISSUE TITLE
Add support for LCD with 4 lines

### ISSUE THREAD

**Issue by vcrn** [mjhouse/ag-lcd#12]
The crate can only control one or two lines of an LCD.

I'll probably have a LCD with 4 lines soon, and will look into if I can implement the functionality to control all 4 lines.

**Comment by mjhouse** [comment]
Awesome. Thanks man.

**Comment by JohnTheCoolingFan** [comment]
I've done a bit of research and testing with my 20x4 LCD. In one line mode, it uses lines 1 and 3, and in two line mode all lines are used in this order: 1, 3, 2, 4

So, I think it just needs some tweaks to allow setting cursor position and a `Lines::FourLines` mode to avoid confusion.
