### ISSUE TITLE
Nano examples not working for boards using new bootloader

### ISSUE THREAD

**Issue by vcrn** [mjhouse/ag-lcd#16]
The latest `ravedude` (v0.1.4) can't flash to Arduino Nano boards that uses the new bootloader (manufactured after January 2018, if I've understood it correctly). A solution has been implemented in `ravedude` (https://github.com/Rahix/avr-hal/pull/247) but has not been released yet.

When a new version of `ravedude` is released, you'll be able to flash to the newer Nano boards with `ravedude nano-new`. At that point, it's probably a good idea to either put a note in the examples/README explaining how to modify the provided Nano examples, or copy-paste the examples and simply change the argument in the runners.

In the meantime, there's a workaround: change the argument to `ravedude` from `nano` to `uno`, or clone the latest commit of `ravedude` and use it to flash your board.

I've asked the maintainer of `ravedude` if they have some estimate of when the new version is to be released.

**Comment by vcrn** [comment]
`ravedude` has a new version (0.1.5) where `nano-new` argument can be used to flash new Nano boards.

Since it should just be a matter of appending "-new" to the argument "nano" in the Nano examples to make them work, it seems a bit excessive to have separate examples for nano-new. What do you say about just adding some info in the README?

**Comment by mjhouse** [comment]
@vcrn Yeah, if you want to throw a note in the README, that's cool

**Comment by vcrn** [comment]
I saw now that I left this opened despite adding text to the examples/README as per your suggestion some months ago. So I'm closing this since it's done!

**Comment by mjhouse** [comment]
Thanks @vcrn
