### ISSUE TITLE
Support i2c interface

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [mjhouse/ag-lcd#22]
This is a request for support of connecting the display using PCF8574 I2C expander board. If there is an alternative crate (that supports both 16x2 and 20x4), please point me to it.

**Comment by mjhouse** [comment]
@JohnTheCoolingFan I'm not aware of one. Off the top of my head it doesn't seem like a large development effort to add that functionality but I'm not actively expanding this library anymore. I'll be happy to review changes and merge pull requests if you add the feature yourself, however.

**Comment by zeenix** [comment]
I'm looking into this. I think I have basic grasp over the I2C protocol after reading [this](https://docs.arduino.cc/learn/communication/wire) Arduino guide but I am finding it difficult to figure out the most important bit: how does the parallel interface maps to the serial? Do I just transfer each pin value in sequence and the adaptor will know what to do?

**Comment by JohnTheCoolingFan** [comment]
Most i2c LCDs of this type use a PCF8574AT or PCF8572T chip, which is a digital interface expansion. There is a crate that allows interacting with it: https://crates.io/crates/port-expander

That library allows getting digital I/O pins that implement embedded-hal I/O traits, so they can be treated just like if the LCD is connected directly. So from this it looks like it's a matter of making an adapter/wrapper that would provide I/O pins for the regular LCD struct from this crate using the lib.
