### ISSUE TITLE
Arduino Uno support

### ISSUE THREAD

**Issue by SyedAhkam** [mjhouse/ag-lcd#3]
Hey! 

Thanks for putting this crate together. It's straightforward and just works.

Today, I tested this crate on my Arduino UNO (with my 1602 display). It works flawlessly.

https://user-images.githubusercontent.com/52673095/147879109-f466d792-86c6-42ba-bcf2-04e2080df922.mp4

(This is not really an issue, but just letting you know it works as you only tested on a nano)

**Comment by mjhouse** [comment]
@SyedAhkam Hey, thanks! I'm sorry I didn't respond, a lot of times I just mass-close notifications because I get a lot of them. I'll add a note in the README about the UNO support.

**Comment by mjhouse** [comment]
Actually, I'm going to keep this open for now

**Comment by SyedAhkam** [comment]
> @SyedAhkam Hey, thanks! I'm sorry I didn't respond, a lot of times I just mass-close notifications because I get a lot of them. I'll add a note in the README about the UNO support.

It's fine, I completely understand. Let me know if you'd want me to further perform some tests to completely assess the UNO support.

**Comment by mjhouse** [comment]
@SyedAhkam I wouldn't say no to a pull request to allow the examples to be built and flashed to an UNO if you wanted to do that.

**Comment by mjhouse** [comment]
Examples are being added in PR #5

**Comment by mjhouse** [comment]
Closing this issue since the pull request for adding an uno example was merged. (#5)
