### ISSUE TITLE
Merging LcdDisplay implementations

### ISSUE THREAD

**Issue by mjhouse** [mjhouse/ag-lcd#32]
During [review of a PR](https://github.com/mjhouse/ag-lcd/pull/28#issuecomment-1525631268), @JohnTheCoolingFan and I discussed merging the two implementations of LcdDisplay by relaxing the requirements on the output pins. This issue is to investigate that and see if it's possible, then implement it if it is.

**Comment by JohnTheCoolingFan** [comment]
Well, first thing that needs to be adressed is `Error` type being required to be `Infallible`. If the requirement of the Error type could be relaxed or removed completely that would make it easy to improve and merge. So the question is: does it need to be `Infallible`? As far as I've seen errors are ignored mostly, no unwraps or other stuff.

**Comment by mjhouse** [comment]
It might have been a holdover from a previous version of the lib. I honestly can't remember.
