### ISSUE TITLE
Versioning and version bump to 0.2.x

### ISSUE THREAD

**Issue by mjhouse** [mjhouse/ag-lcd#35]
@JohnTheCoolingFan @vcrn After the changes for the i2c support, I think we can bump the project to 0.2 and release it on crates.io. I'm not sure what the process should be for when new releases should happen though. Thoughts?

**Comment by JohnTheCoolingFan** [comment]
I think it's reasonable to release a 0.2. Good rule of thumb is to follow the semver rules (which names numbers as major.minor.patch), which means that for versions 0.x minor version increase means new features and/or API change and patch is just for fixes and small improvements that don't change much for the user.

**Comment by vcrn** [comment]
In addition to what @JohnTheCoolingFan said, I think opening an Issue like this is a good idea to discuss whether there's anything additional that should make it into the new version. 

For 0.2, I feel like the README should be updated to mention the I2C feature, and maybe display a short code snippet for I2C?

**Comment by mjhouse** [comment]
I'm cool with that. I'll make an issue for the README update. Can you guys think of anything else that should go in before 0.2?

**Comment by vcrn** [comment]
I don't think so. The only files that seem to matter are the root README and the files in `src/`. I'll look over the code changes in a couple of hours in case there's something missing in the doc comments. I'll probably also try out the code if I have the hardware available, which could be useful in the README unless someone else already has updated it by then with a code snippet.

**Comment by vcrn** [comment]
I've found some small typos/errors in the doc comments which are fixed in #36. I also added some other stuff that went beyond my original intention with the PR. The I2C-feature is great, thanks for all the you two have put into this!

**Comment by mjhouse** [comment]
> I've found some small typos/errors in the doc comments which are fixed in #36. I also added some other stuff that went beyond my original intention with the PR. The I2C-feature is great, thank you for all the work you two have put into this!

It was all @JohnTheCoolingFan.

Also, I forgot to make the README issue, but that change got merged this morning anyway. I'll go ahead and bump the version.

**Comment by mjhouse** [comment]
Bumped the version and re-published on crates.io. I'm going to close this issue, but I'll probably make another for 0.2 -> 0.3 or any other major feature changes.
