### ISSUE TITLE
Working ESP32 example

### ISSUE THREAD

**Issue by benkeil** [mjhouse/ag-lcd#41]
Has someone a working ESP32 example? I don't get it to work...

```rust
let peripherals = Peripherals::take();
let system = peripherals.SYSTEM.split();
let clocks = ClockControl::max(system.clock_control).freeze();
let mut delay = Delay::new(&clocks);

let io = IO::new(peripherals.GPIO, peripherals.IO_MUX);

let mut input = io.pins.gpio21.into_open_drain_output();
let mut i2c = I2C::new(
    peripherals.I2C0,
    io.pins.gpio14,
    io.pins.gpio13,
    100u32.kHz(),
    &clocks,
);
let mut i2c_expander = pcf8574::Pcf8574::new(i2c, true, true, true);
let mut lcd = LcdDisplay::new_pcf8574(&mut i2c_expander, delay)
    .with_cursor(Cursor::On)
    .with_display(Display::On)
    .with_blink(Blink::On)
    .with_lines(Lines::TwoLines)
    .with_cols(16)
    .build();
lcd.clear();
lcd.print("Test message!");
```

I don't get errors, but nothing is displayed.

**Comment by benkeil** [comment]
I have only 2 pins connected (beside GND and 3.3V). Does that mean he needs more than that? Sry l‘m new to this topic.

**Comment by vcrn** [comment]
I don't have an ESP32 available, but according to this [website](https://randomnerdtutorials.com/esp32-i2c-communication-arduino-ide/), it looks like you might need to use pins `GPIO 21` for `sda` and `GPIO 22` for `scl` instead of the ones you are using. What happens if you try this code?

```
let sda = io.pins.gpio21;
let scl = io.pins.gpio22;

let mut i2c = I2C::new(
    peripherals.I2C0,
    sda,
    scl,
    100u32.kHz(),
    &clocks,
);
```
To make sure you're not missing something on a hardware level: are you connecting 4 pins to the LCD? That is, the sda, scl, vcc (3.3 V) and GND?

**Comment by benkeil** [comment]
I used this setup.

<img width="877" alt="Bildschirmfoto 2024-03-25 um 12 32 44" src="https://github.com/mjhouse/ag-lcd/assets/16204452/ef9dcf20-6f5a-4243-9743-06182e09d740">


<img width="877" alt="Bildschirmfoto 2024-03-25 um 12 31 24" src="https://github.com/mjhouse/ag-lcd/assets/16204452/75973b62-1939-4f27-ad9a-549cbfefb2c5">

**Comment by benkeil** [comment]
I have no idea what I'm doing but with this change something is working.

```rust
let mut i2c_expander = pcf8574::Pcf8574a::new(i2c, true, true, true);
let mut lcd = LcdDisplay::new_pcf8574a(&mut i2c_expander, delay)
```

`Pcf8574a` instead of `Pcf8574`

**Comment by vcrn** [comment]
With "something is working", do you mean that the message is being displayed?

**Comment by benkeil** [comment]
Yes, it's working now. ☺️
