### ISSUE TITLE
Can't find 'new_pcf8574'

### ISSUE THREAD

**Issue by DefinitelyNotSimon13** [mjhouse/ag-lcd#42]
So I am just getting started with embedded rust and while trying to use my lcd screen, as seen in the README.md I can't find the 
`LcdDisplay::new_pcf8574()` function anywhere?
Neither does my programm compile, nor can't I find any reference to it in the documentation! What am I missing?

**Comment by vcrn** [comment]
Hi! I assume you're trying to use I2C. Can you get this example to compile?
https://github.com/mjhouse/ag-lcd/tree/master/examples/nano/i2c-print

**Comment by DefinitelyNotSimon13** [comment]
> Hi! I assume you're trying to use I2C. Can you get this example to compile? https://github.com/mjhouse/ag-lcd/tree/master/examples/nano/i2c-print

Dammit, I forgot to add the i2c feature in the Cargo.toml file! After adding that and downgrading port_expander to 0.3 it worked.

Thanks a lot!

**Comment by DefinitelyNotSimon13** [comment]
> Great! And thank you for the info regarding having to downgrade port_expander. Will see if I have time to make this library work with the latest version.

Ofc! Here's the error if it helps:

error[E0308]: mismatched types
  --> src/main.rs:20:61
   |
20 |     let mut lcd: LcdDisplay<_, _> = LcdDisplay::new_pcf8574(&mut i2c_expander, delay)
   |                                     ----------------------- ^^^^^^^^^^^^^^^^^ expected `&mut Pcf8574<_>`, found `&mut Pcf8574<NullMutex<Driver<...>>>`
   |                                     |
   |                                     arguments to this function are incorrect
   |
   = note: `Pcf8574<NullMutex<Driver<...>>>` and `Pcf8574<_>` have similar names, but are actually distinct types
note: `Pcf8574<NullMutex<Driver<...>>>` is defined in crate `port_expander`
  --> /home/simon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/port-expander-0.4.1/src/dev/pcf8574.rs:4:1
   |
4  | pub struct Pcf8574<M>(M);
   | ^^^^^^^^^^^^^^^^^^^^^
note: `Pcf8574<_>` is defined in crate `port_expander`
  --> /home/simon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/port-expander-0.3.1/src/dev/pcf8574.rs:4:1
   |
4  | pub struct Pcf8574<M>(M);
   | ^^^^^^^^^^^^^^^^^^^^^
   = note: perhaps two different versions of crate `port_expander` are being used?
note: associated function defined here
  --> /home/simon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ag-lcd-0.2.0/src/i2c.rs:95:12
   |
95 |     pub fn new_pcf8574(expander: &'a mut Pcf8574<M>, delay: D) -> Self {
   |            ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `arduino-rust` (bin "arduino-rust") due to 1 previous error

**Comment by vcrn** [comment]
Thanks!
