### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by robamu** [mjhouse/ag-lcd#45]
Hi,

I managed to make this work on an RPi Pico, but I had to use a git release because no release was made with the updated embedded-hal. Maybe a release could be made and uploaded to crates-io?

**Comment by mjhouse** [comment]
Oh cool. Yeah, I'll sort that out.

**Comment by mjhouse** [comment]
@robamu Hey, I released [0.3.0](https://crates.io/crates/ag-lcd) with the embedded-hal update.
